export const JWT = {
  ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_LIFE: process.env.JWT_ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_LIFE: process.env.JWT_REFRESH_TOKEN_LIFE,
};
